# Generated by Django 4.0.6 on 2022-07-05 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auto',
        ),
        migrations.DeleteModel(
            name='Localidad',
        ),
    ]
