# Generated by Django 4.0.6 on 2022-07-05 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Edad',
            new_name='Auto',
        ),
        migrations.RenameModel(
            old_name='Telefono',
            new_name='Localidad',
        ),
        migrations.RenameModel(
            old_name='Nombre',
            new_name='Usuario',
        ),
    ]
